### ISSUE TITLE
Support com.github.autopkg preference format

### ISSUE THREAD

**Issue by everetteallen** [Honestpuck/jamf-package-clean#1]
I was able to get the script to use my com.github.autopkg preferences format and was wondering if you would support that since many folks use com.github.autopkg instead of the original jss_importer preferences format.
I was able to 
ln -s ~/Library/Preferences/com.github.autopkg.plist ~/Library/Preferences/JPCImporter.plist

Then modify list-1.2.py lines 17 and 18
base = prefs[‘JSS_URL’] + ‘JSSResource/’
auth = (prefs[‘API_USERNAME’], prefs[‘API_PASSWORD’])

Thanks!

**Comment by Honestpuck** [comment]
@everetteallen I know you can do that but I now have around a dozen places where I use the existing format across all my tools.

Feel free to fork it and make the change, if you do I'll make a note in the README.

**Comment by Honestpuck** [comment]
Actually I just pushed a new version that handles whichever format you like. It seemed the cleanest solution.

**Comment by everetteallen** [comment]
Confirmed Works great for me!  Thank you very much!!
